
const TWITTER_CONSUMER_KEY: string = "IUWEAzTZJLcmfB7RFVErvVyLM";
const TWITTER_CONSUMER_SECRET: string = "bgJDN2WfJwzMZUhWK5lVHp8NklqIOKZ6f5ZscrlrzxPz87BbBf";

export {
  TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET
};
